### ISSUE TITLE
Why not sampling independently for each sample?

### ISSUE THREAD

**Issue by terrencew** [leezu/mxnet_vae#1]
Specifically, in the following:

```
 def  _build_z(self, z_mean, z_log_sigma):
        # broadcast_mul automatically broadcasts the normal symbol to the right shape
        return z_mean + mx.sym.broadcast_mul(
                mx.sym.normal(shape=(1, self.architecture[-1])), mx.sym.exp(z_log_sigma))
```

Here, why not use mx.sym.normal(shape=(batch_size, self.architecture[-1]))

**Comment by leezu** [comment]
In `_build_z` `batch_size` is not yet available. At that stage we are building the mxnet symbol, for which only later when it is binded the `batch_size` is specified. Of course one could pass batch_size to the VAE symbol constructor  (https://github.com/leezu/mxnet_vae/blob/master/vae.py#L22) and then make the change that you proposed. Perhaps it will even work better than the current version. If you want to try it out feel free to send a pull request.
